apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "allure-server.fullname" . }}
  labels:
    {{- include "allure-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "allure-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "allure-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "allure-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: SPRING_DATASOURCE_PASSWORD
            value: {{ .Values.db.password }}
          - name: SPRING_DATASOURCE_URL
            value: {{ .Values.db.host }}
          - name: SPRING_DATASOURCE_USERNAME
            value: {{ .Values.db.user }}
          - name: SPRING_JPA_DATABASE
            value: postgresql
          - name: SPRING_JPA_HIBERNATE_DDL-AUTO
            value: update
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion     }}"
          ports:
          - containerPort: 8080
          resources: {}
          volumeMounts:
          - mountPath: /allure
            name: allure
      volumes:
      - name: allure
        persistentVolumeClaim:
          claimName: {{ include "allure-server.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
