apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "allure-server.fullname" . }}
  labels:
    {{- include "allure-server.labels" . | nindent 4 }}

spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
