# Default values for allure-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: kochetkovma/allure-server
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: []
  hosts:
    - host: example.com
      paths:
      - path: "/"
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

db:
  host: "jdbc:postgresql://localhost:5432/allure"
  user: ""
  password: ""

storage:
  size: 50Gi
